version: 2.1
jobs:
  build:
    working_directory: ~/main
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:  
      - checkout
      - restore_cache:
          name: Restore Cache Gradle
          keys:
            - jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
            - jars-
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          name: Save Cache Gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
          paths:
            - ~/.gradle
      - run:
          name: Android Lint
          command: ./gradlew lint
      - run:
          name: Kotlint Lint
          command: ./gradlew ktlint    

        
